== Concourse Java Scripts
Useful bash scripts that help when building Java projects in http://concouse.ci[Concourse].

=== Importing
Copy `concouse-java.sh` to your project or add it to the docker image you use for building.
Add the following to your build script:

[source,bash]
----
#!/bin/bash
set -e
source <folder>/concourse-java.sh
----

NOTE: This script requires a full bash environment. Some functions also require `git`.

=== Functions

==== setup_symlinks
Adds symlinks for Maven and/or Gradle caches.
The current directory should contain `maven` and/or `gradle` cache folders as created by Concourse.
Syslinks will be created in `$HOME` to `.m2` and `.gradle`.

Setup caches in your task yaml:

[source,yaml]
.task.yml
----
---
platform: linux
image_resource:
  type: docker-image
  ...
inputs:
- name: git-repo
outputs:
- name: built-artifact
caches:
- path: maven
- path: gralde
run:
  ...
----

Then call `setup_symlinks` early in your run script:

[source,bash]
----
setup_symlinks
----

TIP: If `~/.m2` or `~/.gradle` folders already exist, they will not be replaced

==== cleanup_maven_repo
Remove a folder from the local `~/.m2/repository` folder.
This command is often used to ensure that no accidental cache pollution has occurred.

Call with a single maven group identified.
For example:

[source,bash]
----
cleanup_maven_repo com.example.foo
cleanup_maven_repo com.example.bar
----

==== run_maven

Run `./mvnw` from the current directory showing only a limiting subset of the logged output as long as the build succeeds.
If the build fails, the last 3000 lines of output are shown.

For example, given the following call:

[source,bash]
----
run_maven clean install
----

A successful build would show output looking something like this:

[source]
----
./mvnw clean install
[INFO] ------------------------------------------------------------------------
[INFO] Building example-project 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ example-project ---
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle-validation) @ example-project ---
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ example-project ---
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ example-project ---
[INFO] --- build-helper-maven-plugin:1.10:add-test-source (add-test-source) @ example-project ---
[INFO] --- build-helper-maven-plugin:1.10:add-test-resource (add-test-resources) @ example-project ---
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ example-project ---
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ example-project ---
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ example-project ---
----

==== get_revision_from_pom
Gets the `<revision>` property from a `pom.xml` in the current directory.
For example, given the following `pom.xml`:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.example</groupId>
	<artifactId>example-project</artifactId>
	<version>${revision}</version>
	<properties>
		<revision>1.0.0-SNAPSHOT</revision>
		<java.version>1.8</java.version>
	</properties>
</project>
----

The following call would set `version` to `1.0.0-SNAPSHOT`:

[source,bash]
----
version=$( get_revision_from_pom )
----

NOTE: This command relies on `xmllint` being installed

TIP: For details of how you can use `<revision>` in your builds see https://maven.apache.org/maven-ci-friendly.html[Maven CI Friendly Versions]

==== set_revision_to_pom
Sets the `<version>` property to a `pom.xml` in the current directoy.

For example, given the following `pom.xml`:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.example</groupId>
	<artifactId>example-project</artifactId>
	<version>${revision}</version>
	<properties>
		<revision>1.0.0-SNAPSHOT</revision>
		<java.version>1.8</java.version>
	</properties>
</project>
----

The following call would set `version` to `2.0.0`:

[source,bash]
----
set_revision_to_pom "2.0.0"
----

TIP: For details of how you can use `<revision>` in your builds see https://maven.apache.org/maven-ci-friendly.html[Maven CI Friendly Versions]

=== Contributing
See link:CONTRIBUTING.adoc[CONTRIBUTING.adoc] for details of how to contribute.
